### ISSUE TITLE
How to contact your web service with a REST Client ?

### ISSUE THREAD

**Issue by memento** [philipsorst/angular-rest-springsecurity#28]
Hi,

Tanks for you work. 

Can you tell us more about how to contact (only) your REST back end with Postman (example). 
What url do we have to enter ?
For a local test, is it this one : http://localhost:8080/angular-rest-springsecurity/rest/user/authenticate ?

What type of authentication do we have to choose within the client ?

What's the scenario you have in mind ?

Best regards !

**Comment by philipsorst** [comment]
Hi,

all REST resources are available unter the "rest/" path. Generally you will use the "user/authenticate" path in order to obtain an access token by providing the username and password. Any subsequent (authenticated) requests to the REST API will the in include this access token, either by passing it in an "X-Auth-Token" Header or by appending it as a "?token=<token>" parameter.

Hope that helps, regards

Philip

**Comment by memento** [comment]
Thanks !

**Comment by philipsorst** [comment]
Ok, to point that out, you need to perform a POST request with with the "username" and "password" parameters encoded as form parameters.

**Comment by memento** [comment]
Thank you !
